[tool.towncrier]
name = "Changes in"
version = "1.2.3"
filename = "CHANGES.rst"
directory = "changelog.d"
template = "changelog.d/_template.rst"
#issue_format = "dfdsds [\\#{issue}](https://github.com/vector-im/element-ios/issues/{issue})"

[[tool.towncrier.type]]
    directory = "feature"
    name = "‚ú® Features"
    showcontent = true

[[tool.towncrier.type]]
    directory = "bugfix"
    name = "üêõ Bugfixes"
    showcontent = true

[[tool.towncrier.type]]
    directory = "build"
    name = "üß± Build"
    showcontent = true
