[tool.towncrier]
name = "Changes in"
filename = "CHANGES.rst"
directory = "changelog.d"
template = "changelog.d/_template.md.jinja"

[[tool.towncrier.type]]
    directory = "feature"
    name = "âœ¨ Features"
    showcontent = true

[[tool.towncrier.type]]
    directory = "bugfix"
    name = "ğŸ› Bugfixes"
    showcontent = true

[[tool.towncrier.type]]
    directory = "build"
    name = "ğŸ§± Build"
    showcontent = true
